version: '3.7'
services:

  notifications-hub:
    build: ./notification-hub
    container_name: texas-real-foods-notifications-hub
    networks:
    - texas-real-foods
    - core

networks:
  core:
    name: core
  texas-real-foods:
    name: texas-real-foods